print("""
=== 21 QUESTIONS GAME:
DIG DEEP WITH FUN AND FLIRTY QUESTIONS===
""")
print()

print("\033[31m","A fun way to get to know each your faves even better","\033[0m")
print()
info = input("Enter your name: ")
info1 = input("1.  What's the weirdest dream you've ever had?: ")
info2 = input("2. If you could travel to any year in a time machine, what year would you choose and why?: ")
info3 = input("3. If you could change one thing about yourself, what would it be?")
info4 = input("4. What's one of the most fun childhood memories you have?")
info5 = input("5. If you could have dinner with a famous person (living or dead), who would you choose?")
info6 = input("6. What's your favorite movie to watch over and over again?")
print()
info7 = input("7. What's your favorite season of the year?")
info8 = input("8. Who is your celebrity crush?")
info9 = input("9. What's your biggest fear?")
info10 = input("10. What's the wildest thing you've ever done?")
info11 = input("11. What's the best advice you've ever received?")
print()
info12 = input("12. What's a bad habit you had that you've been able to overcome?")
info13 = input("13. What's your dream road trip destination?")
info14 = input("14. What's your favorite food of all time?")
info15 = input("15. What are three items on your bucket list?")
info16 = input("16. What's your biggest regret?")
info17 = input("17. What's your favorite thing about yourself?")
info18 = input("18. What's the weirdest thing in your closet?")
print()
info19 = input("19. If you had to guess what people appreciate you the most, what would you say?")
info20 = input("20. What's your dream job?")
info21 = input("21. If you could be a part of a family on any TV show, which family would you choose?")
print()
print("user name is: ", info, "\n" "wired dream: ", info1, "\n" "the year user would like to back in time to and why: ", info2, "\n" "one thing user would like to change about his or herself" ,info3, "\n" "favourite memory as a child: ",info4, "\n" "famous person u would like to have dinner with: ",info5, "\n" "favourite movie: ",info6, "\n" "favourite season of the year",info7, "\n" "celebrity crush: ",info8, "\n" "Biggest fear: ",info9, "\n" "widest thing you have ever done: ",info10, "\n" "best advice you have ever received: ",info11, "\n" "bad habit you have overcome: ",info12, "\n" "your dream road destination: ",info13, "\n" "favourite food of all time", info14, "\n" "Three items on your bucket list",info15, "\n" "Biggest regret: ",info16, "\n" "favourite about yourself: ",info17, "\n" "weirdest thing in your closet: ",info18, "\n" "people who appreciate you the most: ",info19, "\n" "What's your dream job: ",info20, "\n" "If you could be a part of a family on any TV show, which family would you choose?: ", info21)